### ISSUE TITLE
Добавить в список тестового студента

### ISSUE THREAD

**Issue by markinads** [sortedmap/mipt202402#22]

**Comment by faizr2** [comment]
Даша, спасибо вы такая отзывчивая! А сделать-то мне что? Добавить что-нибудь, куда-нибудь, или удалить?

**Comment by faizr2** [comment]
А! Поняла, сейчас соображу!

**Comment by faizr2** [comment]
Даша, спасибо за задание, я немного притормозила, не увидела, что задание в заголовке :) а потом думала над где pull-request, сначала думала, что его надо на проверку отправить, и тот кто задал задание примет, и что-то там понажимала. но в конце-концов, и pull request и merged сделала сама. Правильно? И вообще правильно ли я поняла и сделала ваше задание?
